---
apiVersion: v1
kind: Service
metadata:
  annotations:
    derrick.service.type: nodeport
    derrick.version: 0.0.24
  labels:
    derrick.service: Mxonline3
  name: Mxonline3
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    derrick.service: Mxonline3
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    derrick.version: 0.0.24
  labels:
    derrick.service: Mxonline3
  name: Mxonline3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        derrick.service: Mxonline3
    spec:
      containers:
      - image: registry.cn-beijing.aliyuncs.com/dockerhhf/derrick:v01
        name: web
        ports:
        - containerPort: 8000